### ISSUE TITLE
Tree should be a instance of `frappe.utils.nestedset.NestedSet`

### ISSUE THREAD

**Issue by MaxMorais** [revant/tree_view#1]
@revant , in your  example you use `Document` as base class, but it dont implement the methods like `update_nsm` the class that implement this method is `frappe.utils.nestedset.NestedSet`.

Using `NestedSet` class, you only need create the required fields, and nothing more.

**Comment by revant** [comment]
> Using NestedSet class, you only need create the required fields, and nothing more.

What are the list of fields required?

changed tree.py to:

```
from __future__ import unicode_literals
import frappe
from frappe import _
from frappe.utils.nestedset import NestedSet

class Tree(NestedSet):
    pass
```

fields in current model - https://revant.github.io/tree_view/current/models/tree_view/tree.html
viz. tree_name, parent_tree, is_group, lft, rgt and old_parent

I got error AttributeError: 'Tree' object has no attribute 'nsm_parent_field'

```
Traceback (innermost last):
  File "/home/revant/frappe-bench/apps/frappe/frappe/app.py", line 57, in application
    response = frappe.handler.handle()
  File "/home/revant/frappe-bench/apps/frappe/frappe/handler.py", line 19, in handle
    execute_cmd(cmd)
  File "/home/revant/frappe-bench/apps/frappe/frappe/handler.py", line 36, in execute_cmd
    ret = frappe.call(method, **frappe.form_dict)
  File "/home/revant/frappe-bench/apps/frappe/frappe/__init__.py", line 806, in call
    return fn(*args, **newargs)
  File "/home/revant/frappe-bench/apps/tree_view/tree_view/tree_view/page/tree_browser/tree_browser.py", line 35, in add_node
    doc.save()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 235, in save
    self.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 211, in insert
    self.run_post_save_methods()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 635, in run_post_save_methods
    self.run_method("on_update")
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 579, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 735, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 718, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 573, in 
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 186, in on_update
    self.validate_ledger()
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 234, in validate_ledger
    (self.doctype, self.nsm_parent_field, '%s'), (self.name)):
 AttributeError: 'Tree' object has no attribute 'nsm_parent_field'
```

Should I rename parent_tree to nsm_parent_field?
Or should I add new nsm_parent_field?

**Comment by revant** [comment]
I just renamed parent_tree to nsm_parent_field.
When I try to install / reinstall tree_view app now it shows following error

```
revant@revant-laptop:~/frappe-bench$ bench install-app tree_view
Installing tree_view...
Updating tree_view                  : [========================================]
Installing fixtures...
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 79, in <module>
    main()
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 16, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands.py", line 29, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/commands.py", line 163, in install_app
    _install_app(app, verbose=context.verbose)
  File "/home/revant/frappe-bench/apps/frappe/frappe/installer.py", line 137, in install_app
    sync_fixtures(name)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/fixtures.py", line 23, in sync_fixtures
    import_doc(frappe.get_app_path(app, "fixtures", fname), ignore_links=True, overwrite=True)
  File "/home/revant/frappe-bench/apps/frappe/frappe/core/page/data_import_tool/data_import_tool.py", line 90, in import_doc
    frappe.modules.import_file.import_file_by_path(f, data_import=True, force=True, pre_process=pre_process)
  File "/home/revant/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 54, in import_file_by_path
    import_doc(doc, force=force, data_import=data_import, pre_process=pre_process)
  File "/home/revant/frappe-bench/apps/frappe/frappe/modules/import_file.py", line 122, in import_doc
    doc.insert()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 211, in insert
    self.run_post_save_methods()
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 635, in run_post_save_methods
    self.run_method("on_update")
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 579, in run_method
    return Document.hook(fn)(self, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 735, in composer
    return composed(self, method, *args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 718, in runner
    add_to_return_value(self, fn(self, *args, **kwargs))
  File "/home/revant/frappe-bench/apps/frappe/frappe/model/document.py", line 573, in <lambda>
    fn = lambda self, *args, **kwargs: getattr(self, method)(*args, **kwargs)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 185, in on_update
    update_nsm(self)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 41, in update_nsm
    update_move_node(doc, pf)
  File "/home/revant/frappe-bench/apps/frappe/frappe/utils/nestedset.py", line 90, in update_move_node
    where name = %s""" % (doc.doctype, '%s'), parent, as_dict=1)[0]
  File "/home/revant/frappe-bench/apps/frappe/frappe/database.py", line 136, in sql
    self._cursor.execute(query, values)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/home/revant/frappe-bench/env/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
_mysql_exceptions.ProgrammingError: (1064, 'You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near \': \'0\', \'dont_update_if_missing\': \'()\', u\'creation\': "\'2016-05-04 10:05:25.518124\' at line 2')

```

**Comment by revant** [comment]
Solved!
https://github.com/revant/tree_view/commit/30475d03933eea54659cc673d73d43b37555f2a5
Thanks for your suggestions! It is easier than before.
